Popup and MemoryAid fix
solved-chinese/app pull request #99
Opened 2021-01-09 08:31 UTC by chenyx512

by Faradawn from #98 
Added Popup. Rendered MemoryAid appear conditionally.
I was not so sure about what to put in the popup. Currently, RadDisplay is displayed.
Anything I need to do, please let me know! Thanks.

2021-01-09 22:25 UTC, Miclin1024 requested changes
Nice job! Here's a couple of things that could use some refinement:
- After the modal is presented, the original interface should be dimmed, and shouldn't be scrollable. This also helps emphasize the pop up as it creates a clear border.
- As shown in the warning and `react-modal` documentation, you should bind modal to the app element (http://reactcommunity.org/react-modal/accessibility/). In our case, the element id would be `learning-app`.
- As per the design, you might want to add box shadow to the modal border, the parameters are in `main.css: box-shadow`.
- The plus and close button should be bigger.

Let me know if you need any help!

2021-01-09 22:30 UTC, Miclin1024 commented on frontend/src/learning/components/ItemDisplay/BreakdownView.js
> +                    <BreakdownChar url={url} qid={qid} />
The `BreakdownRad` and `BreakdownChar` class was not intended for displaying on a full page view. Use `RadDisplay` and `CharDisplay` instead.

2021-01-09 22:32 UTC, Miclin1024 commented on frontend/src/learning/components/ItemDisplay/WordDisplay/PopUp.js
> +//Modal.setAppElement('#root');
Because we don't have an element with `id=root`. As you can see in `frontend/index.js`, the root element id is `learning-app`.

2021-01-09 22:35 UTC, Miclin1024 commented on frontend/src/learning/components/ItemDisplay/WordDisplay/PopUp.js
> +              +
Instead of unicode characters, use Font Awesome icons https://fontawesome.com. (Example in `ItemDisplay/ItemPhonetic.js`)

2021-01-10 10:45 UTC, chenyx512 commented
This looks pretty good to me

2021-01-10 10:46 UTC, merged

2021-01-10 23:02 UTC, Miclin1024 commented
Looks good to me too, I will take a look at the problem you had in #100 and get back to you soon!